# Generated by Django 6.1 on 2026-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rime Co', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('hero_headline', models.CharField(blank=True, max_length=200)),
                ('hero_subheadline', models.CharField(blank=True, max_length=300)),
                ('about_headline', models.CharField(blank=True, max_length=200)),
                ('about_body', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
