# Generated by Django 6.1 on 2026-08-19 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_background_video',
            field=models.FileField(blank=True, null=True, upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_media_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video')], default='none', max_length=10),
        ),
    ]
