# Generated by Django 6.1 on 2026-08-19 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('promo_type', models.CharField(choices=[('bogo', 'Buy X Get Y Free'), ('pack_percent', 'Pack Quantity Discount')], max_length=20)),
                ('buy_quantity', models.PositiveIntegerField(default=1, help_text='Buy X Get Y Free: units to buy.')),
                ('get_quantity', models.PositiveIntegerField(default=1, help_text='Buy X Get Y Free: units given free.')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Pack Quantity Discount: percentage off, e.g. 15.00 for 15%.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('pack', models.ForeignKey(blank=True, help_text='Pack Quantity Discount: the specific pack this applies to, e.g. the 4-Pack.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.productpack')),
                ('product', models.ForeignKey(blank=True, help_text='Buy X Get Y Free: the product this applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
